### ISSUE TITLE
FancyHolograms

### ISSUE THREAD

**Issue by iangry0** [ProjectUnified/UniHologram#108]
Hi, I'm trying to get my plugin to work with all the supported hologram plugins. So far it works perfectly with vanilla, decentholograms and holographicdisplays however when using fancyholograms, I get a console error when loading. I'm using paperspigot and 1.21.3. I have the dependencies and shading setup with maven and it seems to be working properly as the other plugins work.

Created a little [test class ](https://pastebin.com/KY2UHw9h)to test the basic function of creation and again it does not seem to work with fancyholograms
```
Caused by: java.lang.NoClassDefFoundError: de/oliver/fancyholograms/api/HologramData
        at PlayerHolograms-1.0-SNAPSHOT.jar/io.github.projectunified.unihologram.spigot.fancyholograms.FHHologram.<init>(FHHologram.java:47) ~[PlayerHolograms-1.0-SNAPSHOT.jar:?]
        at PlayerHolograms-1.0-SNAPSHOT.jar/io.github.projectunified.unihologram.spigot.fancyholograms.FHHologramProvider.createHologram(FHHologramProvider.java:30) ~[PlayerHolograms-1.0-SNAPSHOT.jar:?]
        at PlayerHolograms-1.0-SNAPSHOT.jar/io.github.projectunified.unihologram.spigot.fancyholograms.FHHologramProvider.createHologram(FHHologramProvider.java:18) ~[PlayerHolograms-1.0-SNAPSHOT.jar:?]
        at PlayerHolograms-1.0-SNAPSHOT.jar/me.iangry.playerholograms.commands.TestCommand.createHologram(TestCommand.java:52) ~[PlayerHolograms-1.0-SNAPSHOT.jar:?]
        at PlayerHolograms-1.0-SNAPSHOT.jar/me.iangry.playerholograms.commands.TestCommand.onCommand(TestCommand.java:43) ~[PlayerHolograms-1.0-SNAPSHOT.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.21.3-R0.1-SNAPSHOT.jar:?]
        ... 27 more
Caused by: java.lang.ClassNotFoundException: de.oliver.fancyholograms.api.HologramData
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:197) ~[paper-api-1.21.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:164) ~[paper-api-1.21.3-R0.1-SNAPSHOT.jar:?]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:528) ~[?:?]
        at PlayerHolograms-1.0-SNAPSHOT.jar/io.github.projectunified.unihologram.spigot.fancyholograms.FHHologram.<init>(FHHologram.java:47) ~[PlayerHolograms-1.0-SNAPSHOT.jar:?]
        at PlayerHolograms-1.0-SNAPSHOT.jar/io.github.projectunified.unihologram.spigot.fancyholograms.FHHologramProvider.createHologram(FHHologramProvider.java:30) ~[PlayerHolograms-1.0-SNAPSHOT.jar:?]
        at PlayerHolograms-1.0-SNAPSHOT.jar/io.github.projectunified.unihologram.spigot.fancyholograms.FHHologramProvider.createHologram(FHHologramProvider.java:18) ~[PlayerHolograms-1.0-SNAPSHOT.jar:?]
        at PlayerHolograms-1.0-SNAPSHOT.jar/me.iangry.playerholograms.commands.TestCommand.createHologram(TestCommand.java:52) ~[PlayerHolograms-1.0-SNAPSHOT.jar:?]
        at PlayerHolograms-1.0-SNAPSHOT.jar/me.iangry.playerholograms.commands.TestCommand.onCommand(TestCommand.java:43) ~[PlayerHolograms-1.0-SNAPSHOT.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.21.3-R0.1-SNAPSHOT.jar:?]
        ... 27 more
> 
```

**Comment by HSGamer** [comment]
Fixed in https://github.com/ProjectUnified/UniHologram/releases/tag/3.1.0
